//   const countries = [
  //     {
  //       value: "United States of America",
  //       label: "United States of America",
  //     },
  //     { value: "Canada", label: "Canada" },
  //     { value: "Mexico", label: "Mexico" },
  //     { value: "Brazil", label: "Brazil" },
  //     { value: "Colombia", label: "Colombia" },
  //     { value: "Argentina", label: "Argentina" },
  //     { value: "Venezuela", label: "Venezuela" },
  //     { value: "Russia", label: "Russia" },
  //     { value: "Ukraine", label: "Ukraine" },
  //     { value: "United Kingdom", label: "United Kingdom" },
  //     { value: "Germany", label: "Germany" },
  //     { value: "Estonia", label: "Estonia" },
  //     { value: "Austria", label: "Austria" },
  //     { value: "Spain", label: "Spain" },
  //     { value: "Hungary", label: "Hungary" },
  //     { value: "Saudi Arabia", label: "Saudi Arabia" },
  //     { value: "Lebanon", label: "Lebanon" },
  //     { value: "India", label: "India" },
  //     { value: "Azerbaijan", label: "Azerbaijan" },
  //     { value: "Indonesia", label: "Indonesia" },
  //     { value: "Iraq", label: "Iraq" },
  //     { value: "Iran", label: "Iran" },
  //     { value: "China", label: "China" },
  //     { value: "Japan", label: "Japan" },
  //     { value: "Kuwait", label: "Kuwait" },
  //     { value: "Nigeria", label: "Nigeria" },
  //     { value: "Angola", label: "Angola" },
  //     { value: "Egypt", label: "Egypt" },
  //     { value: "South Africa", label: "South Africa" },
  //     { value: "Mali, Niger", label: "Mali, Niger" },
  //     { value: "Libya", label: "Libya" },
  //     { value: "Burkina Faso", label: "Burkina Faso" },
  //     { value: "South Sudan", label: "South Sudan" },
  //     { value: "Morocco", label: "Morocco" },
  //     { value: "Australia", label: "Australia" },
  //   ];

export const base_url='http://localhost:8080/api/v1/data';


const country =[
  { value: 'Algeria', label: 'Algeria', region: '' },
  { value: 'Angola', label: 'Angola', region: '' },
  { value: 'Argentina', label: 'Argentina', region: '' },
  { value: 'Australia', label: 'Australia', region: '' },
  { value: 'Austria', label: 'Austria', region: '' },
  { value: 'Azerbaijan', label: 'Azerbaijan', region: '' },
  { value: 'Belize', label: 'Belize', region: '' },
  { value: 'Brazil', label: 'Brazil', region: '' },
  { value: 'Burkina Faso', label: 'Burkina Faso', region: '' },
  { value: 'Canada', label: 'Canada', region: '' },
  { value: 'China', label: 'China', region: '' },
  { value: 'Colombia', label: 'Colombia', region: '' },
  { value: 'Cyprus', label: 'Cyprus', region: '' },
  { value: 'Denmark', label: 'Denmark', region: '' },
  { value: 'Egypt', label: 'Egypt', region: '' },
  { value: 'Estonia', label: 'Estonia', region: '' },
  { value: 'Ethiopia', label: 'Ethiopia', region: '' },
  { value: 'Gabon', label: 'Gabon', region: '' },
  { value: 'Germany', label: 'Germany', region: '' },
  { value: 'Ghana', label: 'Ghana', region: '' },
  { value: 'Greece', label: 'Greece', region: '' },
  { value: 'Hungary', label: 'Hungary', region: '' },
  { value: 'India', label: 'India', region: '' },
  { value: 'Indonesia', label: 'Indonesia', region: '' },
  { value: 'Iran', label: 'Iran', region: '' },
  { value: 'Iraq', label: 'Iraq', region: '' },
  { value: 'Japan', label: 'Japan', region: '' },
  { value: 'Jordan', label: 'Jordan', region: '' },
  { value: 'Kazakhstan', label: 'Kazakhstan', region: '' },
  { value: 'Kuwait', label: 'Kuwait', region: '' },
  { value: 'Lebanon', label: 'Lebanon', region: '' },
  { value: 'Liberia', label: 'Liberia', region: '' },
  { value: 'Libya', label: 'Libya', region: '' },
  { value: 'Malaysia', label: 'Malaysia', region: '' },
  { value: 'Mali', label: 'Mali', region: '' },
  { value: 'Mexico', label: 'Mexico', region: '' },
  { value: 'Morocco', label: 'Morocco', region: '' },
  { value: 'Niger', label: 'Niger', region: '' },
  { value: 'Nigeria', label: 'Nigeria', region: '' },
  { value: 'Norway', label: 'Norway', region: '' },
  { value: 'Oman', label: 'Oman', region: '' },
  { value: 'Pakistan', label: 'Pakistan', region: '' },
  { value: 'Poland', label: 'Poland', region: '' },
  { value: 'Qatar', label: 'Qatar', region: '' },
  { value: 'Russia', label: 'Russia', region: '' },
  { value: 'Saudi Arabia', label: 'Saudi Arabia', region: '' },
  { value: 'South Africa', label: 'South Africa', region: '' },
  { value: 'South Sudan', label: 'South Sudan', region: '' },
  { value: 'Spain', label: 'Spain', region: '' },
  { value: 'Syria', label: 'Syria', region: '' },
  { value: 'Turkey', label: 'Turkey', region: '' },
  { value: 'Ukraine', label: 'Ukraine', region: '' },
  {
    value: 'United Arab Emirates',
    label: 'United Arab Emirates',
    region: ''
  },
  { value: 'United Kingdom', label: 'United Kingdom', region: '' },
  {
    value: 'United States of America',
    label: 'United States of America',
    region: ''
  },
  { value: 'Venezuela', label: 'Venezuela', region: '' }
]
