//   const countries = [
  //     {
  //       value: "United States of America",
  //       label: "United States of America",
  //     },
  //     { value: "Canada", label: "Canada" },
  //     { value: "Mexico", label: "Mexico" },
  //     { value: "Brazil", label: "Brazil" },
  //     { value: "Colombia", label: "Colombia" },
  //     { value: "Argentina", label: "Argentina" },
  //     { value: "Venezuela", label: "Venezuela" },
  //     { value: "Russia", label: "Russia" },
  //     { value: "Ukraine", label: "Ukraine" },
  //     { value: "United Kingdom", label: "United Kingdom" },
  //     { value: "Germany", label: "Germany" },
  //     { value: "Estonia", label: "Estonia" },
  //     { value: "Austria", label: "Austria" },
  //     { value: "Spain", label: "Spain" },
  //     { value: "Hungary", label: "Hungary" },
  //     { value: "Saudi Arabia", label: "Saudi Arabia" },
  //     { value: "Lebanon", label: "Lebanon" },
  //     { value: "India", label: "India" },
  //     { value: "Azerbaijan", label: "Azerbaijan" },
  //     { value: "Indonesia", label: "Indonesia" },
  //     { value: "Iraq", label: "Iraq" },
  //     { value: "Iran", label: "Iran" },
  //     { value: "China", label: "China" },
  //     { value: "Japan", label: "Japan" },
  //     { value: "Kuwait", label: "Kuwait" },
  //     { value: "Nigeria", label: "Nigeria" },
  //     { value: "Angola", label: "Angola" },
  //     { value: "Egypt", label: "Egypt" },
  //     { value: "South Africa", label: "South Africa" },
  //     { value: "Mali, Niger", label: "Mali, Niger" },
  //     { value: "Libya", label: "Libya" },
  //     { value: "Burkina Faso", label: "Burkina Faso" },
  //     { value: "South Sudan", label: "South Sudan" },
  //     { value: "Morocco", label: "Morocco" },
  //     { value: "Australia", label: "Australia" },
  //   ];
