//   const countries = [
//     {
//       value: "United States of America",
//       label: "United States of America",
//     },
//     { value: "Canada", label: "Canada" },
//     { value: "Mexico", label: "Mexico" },
//     { value: "Brazil", label: "Brazil" },
//     { value: "Colombia", label: "Colombia" },
//     { value: "Argentina", label: "Argentina" },
//     { value: "Venezuela", label: "Venezuela" },
//     { value: "Russia", label: "Russia" },
//     { value: "Ukraine", label: "Ukraine" },
//     { value: "United Kingdom", label: "United Kingdom" },
//     { value: "Germany", label: "Germany" },
//     { value: "Estonia", label: "Estonia" },
//     { value: "Austria", label: "Austria" },
//     { value: "Spain", label: "Spain" },
//     { value: "Hungary", label: "Hungary" },
//     { value: "Saudi Arabia", label: "Saudi Arabia" },
//     { value: "Lebanon", label: "Lebanon" },
//     { value: "India", label: "India" },
//     { value: "Azerbaijan", label: "Azerbaijan" },
//     { value: "Indonesia", label: "Indonesia" },
//     { value: "Iraq", label: "Iraq" },
//     { value: "Iran", label: "Iran" },
//     { value: "China", label: "China" },
//     { value: "Japan", label: "Japan" },
//     { value: "Kuwait", label: "Kuwait" },
//     { value: "Nigeria", label: "Nigeria" },
//     { value: "Angola", label: "Angola" },
//     { value: "Egypt", label: "Egypt" },
//     { value: "South Africa", label: "South Africa" },
//     { value: "Mali, Niger", label: "Mali, Niger" },
//     { value: "Libya", label: "Libya" },
//     { value: "Burkina Faso", label: "Burkina Faso" },
//     { value: "South Sudan", label: "South Sudan" },
//     { value: "Morocco", label: "Morocco" },
//     { value: "Australia", label: "Australia" },
//   ];

export const base_url = "http://localhost:8080/api/v1/data";

const countries =[
  { value: "Algeria", label: "Algeria", region: "Northern Africa" },
  { value: "Angola", label: "Angola", region: "Central Africa" },
  { value: "Argentina", label: "Argentina", region: "South America" },
  { value: "Australia", label: "Australia", region: "Oceania" },
  { value: "Austria", label: "Austria", region: "Western Europe" },
  { value: "Azerbaijan", label: "Azerbaijan", region: "Central Asia" },
  { value: "Belize", label: "Belize", region: "Central America" },
  { value: "Brazil", label: "Brazil", region: "South America" },
  { value: "Burkina Faso", label: "Burkina Faso", region: "Western Africa" },
  { value: "Canada", label: "Canada", region: "Northern America" },
  { value: "China", label: "China", region: "Eastern Asia" },
  { value: "Colombia", label: "Colombia", region: "South America" },
  { value: "Cyprus", label: "Cyprus", region: "Western Asia" },
  { value: "Denmark", label: "Denmark", region: "Northern Europe" },
  { value: "Egypt", label: "Egypt", region: "Northern Africa" },
  { value: "Estonia", label: "Estonia", region: "Northern Europe" },
  { value: "Ethiopia", label: "Ethiopia", region: "Eastern Africa" },
  { value: "Gabon", label: "Gabon", region: "Central Africa" },
  { value: "Germany", label: "Germany", region: "Western Europe" },
  { value: "Ghana", label: "Ghana", region: "Western Africa" },
  { value: "Greece", label: "Greece", region: "Southern Europe" },
  { value: "Hungary", label: "Hungary", region: "Eastern Europe" },
  { value: "India", label: "India", region: "Southern Asia" },
  {
    value: "Indonesia",
    label: "Indonesia",
    region: "South-Eastern Asia",
  },
  { value: "Iran", label: "Iran", region: "Southern Asia" },
  { value: "Iraq", label: "Iraq", region: "Western Asia" },
  { value: "Japan", label: "Japan", region: "Eastern Asia" },
  { value: "Jordan", label: "Jordan", region: "Western Asia" },
  { value: "Kazakhstan", label: "Kazakhstan", region: "Central Asia" },
  { value: "Kuwait", label: "Kuwait", region: "Western Asia" },
  { value: "Lebanon", label: "Lebanon", region: "Western Asia" },
  { value: "Liberia", label: "Liberia", region: "Western Africa" },
  { value: "Libya", label: "Libya", region: "Northern Africa" },
  {
    value: "Malaysia",
    label: "Malaysia",
    region: "South-Eastern Asia",
  },
  { value: "Mali", label: "Mali", region: "Western Africa" },
  { value: "Mexico", label: "Mexico", region: "Central America" },
  { value: "Morocco", label: "Morocco", region: "Northern Africa" },
  { value: "Niger", label: "Niger", region: "Western Africa" },
  { value: "Nigeria", label: "Nigeria", region: "Western Africa" },
  { value: "Norway", label: "Norway", region: "Northern Europe" },
  { value: "Oman", label: "Oman", region: "Western Asia" },
  { value: "Pakistan", label: "Pakistan", region: "Southern Asia" },
  { value: "Poland", label: "Poland", region: "Eastern Europe" },
  { value: "Qatar", label: "Qatar", region: "Western Asia" },
  { value: "Russia", label: "Russia", region: "Eastern Europe" },
  { value: "Saudi Arabia", label: "Saudi Arabia", region: "Western Asia" },
  {
    value: "South Africa",
    label: "South Africa",
    region: "Southern Africa",
  },
  {
    value: "South Sudan",
    label: "South Sudan",
    region: "Eastern Africa",
  },
  { value: "Spain", label: "Spain", region: "Southern Europe" },
  { value: "Syria", label: "Syria", region: "Western Asia" },
  { value: "Turkey", label: "Turkey", region: "Western Asia" },
  { value: "Ukraine", label: "Ukraine", region: "Eastern Europe" },
  {
    value: "United Arab Emirates",
    label: "United Arab Emirates",
    region: "Western Asia",
  },
  {
    value: "United Kingdom",
    label: "United Kingdom",
    region: "Northern Europe",
  },
  {
    value: "United States of America",
    label: "United States of America",
    region: "Northern America",
  },
  { value: "Venezuela", label: "Venezuela", region: "South America" },
];

export function formatToDDMMYYYY(dateString) {
  const date = new Date(dateString);

  // Extract parts and pad with leading zeros if necessary
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0"); // Months are 0-indexed in JS
  const year = date.getFullYear();

  return `${day}/${month}/${year}`;
}
